import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import cx from 'classnames';

const contrasts = {
  base: 'bg-white dark:bg-zinc-900',
  low: 'bg-zinc-50 dark:bg-zinc-800',
  med: 'bg-zinc-100 dark:bg-zinc-700',
  medium: 'bg-zinc-100 dark:bg-zinc-600',
  high: 'bg-zinc-200 dark:bg-zinc-500',
  max: 'bg-black dark:bg-white',
};

const elevations = {
  0: 'shadow-none',
  1: 'shadow-sm',
  2: 'shadow-md',
  3: 'shadow-lg',
  4: 'shadow-xl',
  5: 'shadow-2xl',
};

const Surface = ({
  className,
  bordered,
  contrast = 'base',
  elevation,
  ...props
}: any) => {
  // @ts-ignore
  const bg = contrasts[contrast];
  const borderClass = 'border border-zinc-300 dark:border-zinc-500';
  // @ts-ignore
  const shadowClass = elevations[elevation];
  const textColor = 'text-zinc-900 dark:text-zinc-50';
  const classes = cx(
    bg,
    textColor,
    'p-5',
    'rounded-md',
    bordered && borderClass,
    shadowClass,
    className
  );

  return <div className={classes} {...props} />;
};

const TypographyExample = () => {
  return (
    <div className="flex items-center justify-between gap-4">
      <div className="font-bold text-4xl">Aa</div>
      <div className="flex-1">
        <div className="flex flex-col gap-1 text-sm">
          <div>ABCDEFGHIJKLMNOPQRSTUVWXYZ</div>
          <div className="opacity-70">abcdefghijklmnopqrstuvwxyz</div>
          <div className="opacity-50">0123456789!@#$%^&*()</div>
        </div>
      </div>
    </div>
  );
};

const Dark = (props) => <div className="dark" {...props} />;

const SurfaceContrastExample = (props) => (
  <Surface contrast="base" {...props}>
    <Surface contrast="low" {...props}>
      <Surface contrast="med" {...props}>
        <Surface contrast="high" {...props}></Surface>
      </Surface>
    </Surface>
  </Surface>
);

const SurfaceShadowExample = (props) => (
  <Surface elevation={0} {...props}>
    <Surface elevation={1} {...props}>
      <Surface elevation={2} {...props}>
        <Surface elevation={3} {...props}>
          <Surface elevation={4} {...props}>
            <Surface elevation={5} {...props}></Surface>
          </Surface>
        </Surface>
      </Surface>
    </Surface>
  </Surface>
);

const Wrapper = (props) => <div className="p-2" {...props} />;

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="grid grid-cols-2 gap-4 p-4">
          <Surface className="p-12">
            <Surface elevation={5}>
              <TypographyExample />
            </Surface>
          </Surface>

          <Dark>
            <Surface className="p-12">
              <Surface elevation={5}>
                <TypographyExample />
              </Surface>
            </Surface>
          </Dark>

          <Surface className="p-12">
            <Surface contrast="low" elevation={5}>
              <TypographyExample />
            </Surface>
          </Surface>

          <Dark>
            <Surface className="p-12">
              <Surface contrast="low" elevation={5}>
                <TypographyExample />
              </Surface>
            </Surface>
          </Dark>

          <Surface className="p-12">
            <Surface contrast="med" elevation={5}>
              <TypographyExample />
            </Surface>
          </Surface>

          <Dark>
            <Surface className="p-12">
              <Surface contrast="med" elevation={5}>
                <TypographyExample />
              </Surface>
            </Surface>
          </Dark>

          <Surface className="p-12">
            <Surface contrast="high" elevation={5}>
              <TypographyExample />
            </Surface>
          </Surface>

          <Dark>
            <Surface className="p-12">
              <Surface contrast="high" elevation={5}>
                <TypographyExample />
              </Surface>
            </Surface>
          </Dark>

          <SurfaceContrastExample />
          <Dark>
            <SurfaceContrastExample />
          </Dark>

          <SurfaceContrastExample bordered />
          <Dark>
            <SurfaceContrastExample bordered />
          </Dark>

          <SurfaceShadowExample />
          <Dark>
            <SurfaceShadowExample contrast="low" />
          </Dark>

          <SurfaceShadowExample bordered />
          <Dark>
            <SurfaceShadowExample bordered />
          </Dark>

          <SurfaceShadowExample contrast="med" />
          <Dark>
            <SurfaceShadowExample contrast="med" />
          </Dark>
        </div>
      </main>
    </div>
  );
};

export default Home;
