import type { NextPage } from 'next';
import Head from 'next/head';
import cx from 'classnames';
import { Surface, contrasts } from '../components/Surface';

const TypographyExample = () => {
  return (
    <div className="flex items-center justify-between gap-4">
      <div className="font-bold text-4xl">Aa</div>
      <div className="flex-1">
        <div className="flex flex-col gap-1 text-sm">
          <div>ABCDEFGHIJKLMNOPQRSTUVWXYZ</div>
          <div className="opacity-70">abcdefghijklmnopqrstuvwxyz</div>
          <div className="opacity-50">0123456789!@#$%^&*()</div>
        </div>
      </div>
    </div>
  );
};

const controlClasses = cx(
  'h-8 rounded border border-zinc-300 dark:border-zinc-500 w-full outline-none focus:border-blue-500 dark:focus:border-blue-500 py-1 p-2 focus:ring-2 focus:ring-blue-400/70',
  contrasts.min
);

const Button = (props) => (
  <button {...props} className={cx(controlClasses, props.className)} />
);
const TextInput = (props) => (
  <input {...props} className={cx(controlClasses, props.className)} />
);
const Textarea = (props) => (
  <textarea
    {...props}
    className={cx(controlClasses, 'min-h-[80px]', props.className)}
  />
);

const Dark = (props) => <div className="dark" {...props} />;

const SurfaceContrastExample = (props) => (
  <Surface contrast="min" {...props}>
    <Surface contrast="low" {...props}>
      <Surface contrast="med" {...props}>
        <Surface contrast="high" {...props}></Surface>
      </Surface>
    </Surface>
  </Surface>
);

const SurfaceShadowExample = (props) => (
  <Surface elevation={0} {...props}>
    <Surface elevation={1} {...props}>
      <Surface elevation={2} {...props}>
        <Surface elevation={3} {...props}>
          <Surface elevation={4} {...props}>
            <Surface elevation={5} {...props}></Surface>
          </Surface>
        </Surface>
      </Surface>
    </Surface>
  </Surface>
);

const BasicAppExample = () => (
  <Surface contrast="med" className="p-0">
    <div className="flex flex-row items-stretch">
      <div className="w-44">
        <Surface className="p-12 h-full" bordered>
          <h1>Hello</h1>
        </Surface>
      </div>
      <div className="flex-1 p-8">
        <div className="flex flex-col gap-4">
          <Surface rounded bordered>
            Hello
          </Surface>
          <Surface rounded bordered>
            Hello
          </Surface>
        </div>
      </div>
    </div>
  </Surface>
);

const ControlExample = () => (
  <div className="flex flex-col gap-4">
    <Button>Button</Button>
    <TextInput />
    <Textarea />
  </div>
);

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="grid md:grid-cols-2 gap-4 p-4">
          <Surface className="p-12">
            <Surface elevation={5}>
              <TypographyExample />
            </Surface>
          </Surface>

          <Dark>
            <Surface className="p-12" contrast="min">
              <Surface elevation={5}>
                <TypographyExample />
              </Surface>
            </Surface>
          </Dark>

          <Surface className="p-12" contrast="min">
            <Surface contrast="low" elevation={5}>
              <TypographyExample />
            </Surface>
          </Surface>

          <Dark>
            <Surface className="p-12" contrast="min">
              <Surface contrast="low" elevation={5}>
                <TypographyExample />
              </Surface>
            </Surface>
          </Dark>

          <Surface className="p-12" contrast="min">
            <Surface contrast="med" elevation={5}>
              <TypographyExample />
            </Surface>
          </Surface>

          <Dark>
            <Surface className="p-12" contrast="min">
              <Surface contrast="med" elevation={5}>
                <TypographyExample />
              </Surface>
            </Surface>
          </Dark>

          <Surface className="p-12" contrast="min">
            <Surface contrast="high" elevation={5}>
              <TypographyExample />
            </Surface>
          </Surface>

          <Dark>
            <Surface className="p-12" contrast="min">
              <Surface contrast="high" elevation={5}>
                <TypographyExample />
              </Surface>
            </Surface>
          </Dark>

          <SurfaceContrastExample />
          <Dark>
            <SurfaceContrastExample />
          </Dark>

          <SurfaceContrastExample bordered />
          <Dark>
            <SurfaceContrastExample bordered />
          </Dark>

          <SurfaceShadowExample />
          <Dark>
            <SurfaceShadowExample contrast="low" />
          </Dark>

          <SurfaceShadowExample bordered />
          <Dark>
            <SurfaceShadowExample bordered />
          </Dark>

          <SurfaceShadowExample contrast="base" />
          <Dark>
            <SurfaceShadowExample contrast="base" />
          </Dark>

          <SurfaceShadowExample contrast="low" />
          <Dark>
            <SurfaceShadowExample contrast="low" />
          </Dark>

          <SurfaceShadowExample contrast="med" />
          <Dark>
            <SurfaceShadowExample contrast="med" />
          </Dark>

          <SurfaceShadowExample contrast="high" />
          <Dark>
            <SurfaceShadowExample contrast="high" />
          </Dark>

          <BasicAppExample />
          <Dark>
            <BasicAppExample />
          </Dark>

          <Surface contrast="low">
            <ControlExample />
          </Surface>

          <Dark>
            <Surface contrast="low">
              <ControlExample />
            </Surface>
          </Dark>
        </div>
      </main>
    </div>
  );
};

export default Home;
